version: '3.7'

services:
  grafana:
    container_name: ${PROJECT:-centralised-logging-and-visualisations-}grafana
    image: grafana/grafana:latest-ubuntu
    ports:
      - '3000:3000'
    restart: on-failure
    depends_on:
      - loki

  loki:
    container_name: ${PROJECT:-centralised-logging-and-visualisations-}loki
    image: grafana/loki:latest
    ports:
      - '3100:3100'
    volumes:
      - type: bind
        source: $PWD/loki-config.yaml
        target: /etc/loki/local-config.yaml
    restart: on-failure

  app:
    container_name: ${PROJECT:-centralised-logging-and-visualisations-}app
    image: blog.mariossimou.dev/centralised-logging-and-visualisations-app:latest
    build:
      context: ./services/app
      dockerfile: ./deployments/app.dockerfile
    privileged: true
    ports:
      - '8080:8080'
    restart: on-failure
    depends_on:
      - loki
      - grafana
